import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Figtree } from "next/font/google";

import "./globals.css";

const inter = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Toaster position="top-center" reverseOrder={false} />
        </div>
        {children}
      </body>
    </html>
  );
}
